id = "vscode-dark"
name = "VSCode Dark Themes"
version = "0.1.0"
schema_version = 1
authors = ["Converted from VSCode Dark Theme"]
description = "VSCode Dark Themes for Zed"
repository = "https://github.com/modif93/zed-vscode-theme"
